# Maintainers - do not change without permission
sethvargo: 'maintainer'

# Members - to add a new member, add their GitHub username and propose a PR with
# them as a reviewer.
#
#     github_username: 'member'
#
drevell: 'member'
yolocs: 'member'
