name: 'terraform'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  terraform:
    name: 'terraform'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3

      - uses: 'hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1' # ratchet:hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.x'

      - run: 'terraform init -upgrade'
        working-directory: './terraform'

      - run: 'terraform fmt -diff -check'
        working-directory: './terraform'

      - run: 'terraform validate'
        working-directory: './terraform'

      - run: 'terraform apply -auto-approve'
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: '${{ secrets.ORGANIZATION_PAT }}'
        working-directory: './terraform'
