name: 'terraform'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  schedule:
  - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  terraform:
    name: 'terraform'
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v2'

    - uses: 'hashicorp/setup-terraform@v1'
      with:
        terraform_version: '1.1.x'

    - run: 'terraform init -upgrade'
      working-directory: './terraform'

    - run: 'terraform fmt -diff -check'
      working-directory: './terraform'

    - run: 'terraform validate'
      working-directory: './terraform'

    - run: 'terraform apply -auto-approve'
      env:
        GITHUB_TOKEN: '${{ secrets.ORGANIZATION_PAT }}'
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
